import React, { FormEvent, useState } from "react";
import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, WorkspacePending } from "@/pages/Console";
import { Archive, CheckCircle2, CircleAlert, Download, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import "../audit-anchoring.css";

const providers = ["s3_object_lock", "azure_immutable_blob", "gcs_bucket_lock", "other_worm"] as const;
const modes = ["governance", "compliance", "time_based", "legal_hold", "locked_retention"] as const;
function display(value: string | null | undefined) { return value ? value.replace(/_/g, " ") : "Not recorded"; }

export default function AuditAnchoringPage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const utils = trpc.useUtils();
  const anchors = trpc.auditAnchoring.list.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const prepare = trpc.auditAnchoring.prepare.useMutation({ onSuccess: () => { toast.success("Ledger-head proof bundle prepared. Retain it under the customer’s immutable policy before recording a receipt."); utils.auditAnchoring.list.invalidate(); }, onError: error => toast.error(error.message) });
  const receipt = trpc.auditAnchoring.recordExternalReceipt.useMutation({ onSuccess: () => { toast.success("External retention receipt recorded as an administrator attestation."); utils.auditAnchoring.list.invalidate(); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ anchorId: 0, provider: "s3_object_lock" as typeof providers[number], externalReference: "", retentionMode: "compliance" as typeof modes[number] });
  if (!ready || !organizationId) return <WorkspacePending />;
  const submitReceipt = (event: FormEvent) => { event.preventDefault(); if (!form.anchorId) return toast.error("Choose a prepared audit anchor first."); receipt.mutate({ organizationId, ...form }); };
  return <PageFrame eyebrow="Independent evidence retention" title="Prepare a ledger head. Retain it outside AgentFence." description="AgentFence prepares a signed ledger-head proof bundle and records a customer administrator’s external retention receipt. The product does not verify provider-side WORM enforcement without a configured customer retention integration." action={<Badge tone="warn">Customer WORM required</Badge>}>
    <section className="anchor-boundary"><LockKeyhole size={19} /><div><strong>Evidence boundary</strong><span>The prepared bundle is platform evidence only. Independent immutability begins only after your organization stores it in a customer-controlled WORM service and validates that service’s retention policy.</span></div></section>
    <section className="anchor-grid"><article className="console-card anchor-card"><div className="card-heading"><div><p className="card-kicker">Step 1 · ledger checkpoint</p><h2>Prepare an export-ready proof bundle</h2><p className="widget-subtitle">The bundle includes the current tenant ledger head, its sequence, event hash, predecessor hash, timestamp, and deterministic anchor hash. It contains no raw action payloads or credentials.</p></div><Archive size={22} className="text-cyan-300" /></div><button className="btn-primary" type="button" disabled={prepare.isPending} onClick={() => prepare.mutate({ organizationId })}>{prepare.isPending ? <Loader2 className="animate-spin" size={16} /> : <ShieldCheck size={16} />} Prepare ledger checkpoint</button><div className="anchor-facts"><span><CheckCircle2 size={14} /> Hash-linked ledger head</span><span><CheckCircle2 size={14} /> Privacy-safe proof file</span><span><CircleAlert size={14} /> No automatic WORM claim</span></div></article>
      <form className="console-card anchor-card" onSubmit={submitReceipt}><div className="card-heading"><div><p className="card-kicker">Step 2 · external receipt</p><h2>Record customer retention evidence</h2><p className="widget-subtitle">Record only the immutable-storage location and retention mode after your storage administrator has retained the prepared proof. Never paste access keys, signatures, or storage credentials.</p></div><LockKeyhole size={21} className="text-amber-300" /></div><label className="field-wrap"><span className="field-label">Prepared ledger checkpoint</span><select value={form.anchorId} required onChange={event => setForm({ ...form, anchorId: Number(event.target.value) })}><option value={0}>Select a prepared checkpoint</option>{(anchors.data ?? []).filter(anchor => anchor.status === "prepared").map(anchor => <option key={anchor.id} value={anchor.id}>Sequence {anchor.ledgerSequence} · {anchor.anchorHash.slice(0, 12)}…</option>)}</select></label><label className="field-wrap"><span className="field-label">Retention provider</span><select value={form.provider} onChange={event => setForm({ ...form, provider: event.target.value as typeof providers[number] })}>{providers.map(provider => <option key={provider} value={provider}>{provider.replace(/_/g, " ")}</option>)}</select></label><label className="field-wrap"><span className="field-label">Non-secret retention location</span><input required value={form.externalReference} onChange={event => setForm({ ...form, externalReference: event.target.value })} placeholder="s3://customer-worm-bucket/agentfence/audit" /><span className="field-hint">Permitted forms: credential-free <code>s3://</code>, <code>gs://</code>, or HTTPS locations. Queries, tokens, and signatures are rejected.</span></label><label className="field-wrap"><span className="field-label">Retention mode</span><select value={form.retentionMode} onChange={event => setForm({ ...form, retentionMode: event.target.value as typeof modes[number] })}>{modes.map(mode => <option key={mode} value={mode}>{mode.replace(/_/g, " ")}</option>)}</select></label><button className="btn-primary" disabled={receipt.isPending}>{receipt.isPending ? <Loader2 className="animate-spin" size={16} /> : <CheckCircle2 size={16} />} Record external receipt</button></form></section>
    <section className="anchor-ledger" aria-label="Prepared audit anchors"><div className="section-heading"><div><p className="card-kicker">Anchor history</p><h2>Customer-retention evidence</h2></div><Badge tone="info">{anchors.data?.length ?? 0} checkpoints</Badge></div>{anchors.isLoading ? <div className="console-card anchor-loading"><Loader2 size={19} className="animate-spin" /> Loading anchor history…</div> : (anchors.data ?? []).length === 0 ? <div className="console-card anchor-loading"><Archive size={19} /> No anchor has been prepared. Start with the current ledger head.</div> : <div className="anchor-stack">{anchors.data?.map(anchor => <article className="console-card anchor-row" key={anchor.id}><div><p className="card-kicker">Ledger sequence {anchor.ledgerSequence}</p><h3>{anchor.status === "external_receipt_recorded" ? "External receipt recorded" : "Export-ready checkpoint"}</h3><code>{anchor.anchorHash}</code></div><div className="anchor-row-facts"><span><strong>Storage bundle</strong><a href={anchor.storageUrl} target="_blank" rel="noreferrer"><Download size={13} /> Download proof</a></span><span><strong>Retention provider</strong>{display(anchor.externalProvider)}</span><span><strong>Retention mode</strong>{display(anchor.retentionMode)}</span><span><strong>Receipt</strong>{anchor.receiptRecordedAt ? new Date(anchor.receiptRecordedAt).toLocaleString() : "Not yet recorded"}</span></div><p>{anchor.status === "external_receipt_recorded" ? `A customer administrator recorded ${anchor.externalReference}. Provider-side WORM enforcement still requires the customer’s storage-policy verification.` : "Prepare this file for customer-controlled WORM retention, then record the non-secret receipt location."}</p></article>)}</div>}</section>
  </PageFrame>;
}
