import React from "react";
import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, WorkspacePending } from "@/pages/Console";
import { Activity, CircleAlert, EyeOff, Loader2, Network, ShieldCheck, Wrench } from "lucide-react";
import "../coverage-posture.css";

function tone(state: string) { return state === "observed" ? "good" : state === "not_expected" ? "info" : "warn"; }
function label(state: string) { return state === "policy_gap" ? "Policy gap" : state === "evidence_gap" ? "Evidence gap" : state === "not_expected" ? "Not expected" : "Observed"; }

export default function CoveragePosturePage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const posture = trpc.coveragePosture.get.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  if (!ready || !organizationId) return <WorkspacePending />;
  const data = posture.data;
  return <PageFrame eyebrow="Enforcement coverage" title="Measure what AgentFence can prove—not what it cannot see" description="Coverage posture correlates registered integrations, active policies, and governed action evidence. It makes missing evidence explicit and does not claim network-level telemetry for direct agent bypass paths." action={<Badge tone="warn">Integrated-path evidence only</Badge>}>
    <section className="coverage-boundary" aria-label="Coverage measurement boundary"><EyeOff size={19} /><div><strong>Direct-call boundary remains visible</strong><span>A missing action record is an evidence gap, not proof of bypass. SDK, browser-wrapper, and Native MCP Gateway enforcement must be paired with target-system permissions and egress controls.</span></div></section>
    {posture.isLoading ? <div className="console-card coverage-loading"><Loader2 size={20} className="animate-spin" /> Calculating tenant coverage posture…</div> : !data ? <div className="console-card coverage-loading"><CircleAlert size={20} /> Coverage posture is unavailable. Refresh the workspace and try again.</div> : <>
      <section className="coverage-kpis" aria-label="Coverage posture summary"><article className="console-card coverage-kpi"><span>Active agents</span><strong>{data.summary.activeAgents}</strong><small>{data.summary.registeredAgents} registered identities</small></article><article className="console-card coverage-kpi good"><span>Observed integrations</span><strong>{data.summary.observedActiveAgents}</strong><small>With governed evidence in {data.observation.days} days</small></article><article className="console-card coverage-kpi warn"><span>Policy gaps</span><strong>{data.summary.policyGaps}</strong><small>Active agents without an applicable active policy</small></article><article className="console-card coverage-kpi warn"><span>Evidence gaps</span><strong>{data.summary.evidenceGaps}</strong><small>Active agents with no governed action record</small></article></section>
      <section className="coverage-grid"><article className="console-card coverage-card"><div className="card-heading"><div><p className="card-kicker">Agent evidence inventory</p><h2>Registered control-path posture</h2><p className="widget-subtitle">Observation begins {new Date(data.observation.start).toLocaleDateString()}. Only AgentFence-recorded actions are counted.</p></div><Activity size={21} className="text-cyan-300" /></div><div className="coverage-agent-list">{data.items.length === 0 ? <p className="coverage-empty">No agents are registered in this workspace yet.</p> : data.items.map(agent => <article className="coverage-agent" key={agent.id}><div className="coverage-agent-title"><div><strong>{agent.name}</strong><span>{agent.identity} · {agent.environment} · {agent.riskLevel} risk</span></div><Badge tone={tone(agent.state)}>{label(agent.state)}</Badge></div><div className="coverage-agent-facts"><span><strong>{agent.applicablePolicyCount}</strong> applicable policies</span><span><strong>{agent.governedActionCount}</strong> governed actions</span><span><strong>{agent.allowedCount}</strong> allowed</span><span><strong>{agent.blockedOrHeldCount}</strong> blocked or held</span></div><p>{agent.explanation}</p></article>)}</div></article>
      <aside className="coverage-side-stack"><article className="console-card coverage-card"><div className="card-heading"><div><p className="card-kicker">MCP control coverage</p><h2>Reviewed tool surface</h2></div><Network size={20} className="text-cyan-300" /></div><div className="coverage-mcp-facts"><span><strong>{data.mcp.registeredServers}</strong> registered servers</span><span><strong>{data.mcp.trustedServers}</strong> trusted servers</span><span><strong>{data.mcp.enabledTools}</strong> enabled tools</span></div><p className="widget-subtitle">Only trusted public-HTTPS servers with enabled tools may receive a runtime-scoped proxied call.</p></article><article className="console-card coverage-card coverage-limitations"><div className="card-heading"><div><p className="card-kicker">Measurement limits</p><h2>What this report does not claim</h2></div><Wrench size={20} className="text-amber-300" /></div><ul>{data.limitations.map(limit => <li key={limit}><CircleAlert size={14} /> {limit}</li>)}</ul><div className="coverage-next"><ShieldCheck size={16} /><span>Next control: pair every production integration with target-side least privilege, egress restriction, and an owner-reviewed exception record.</span></div></article></aside></section>
    </>}
  </PageFrame>;
}
