import React, { useEffect, useMemo, useState } from "react";
import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, WorkspacePending } from "@/pages/Console";
import { Activity, BellRing, CircleAlert, LockKeyhole, PauseCircle, PlayCircle, RefreshCw, ShieldAlert, Siren, ToggleLeft, ToggleRight } from "lucide-react";
import { toast } from "sonner";
import "../incident-response.css";

function decisionTone(value: string) { return value === "blocked" ? "danger" : value === "approval_required" ? "warn" : "info"; }
function severityTone(value: string) { return value === "critical" ? "danger" : value === "high" ? "warn" : "info"; }

export default function IncidentResponsePage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const utils = trpc.useUtils();
  const input = { organizationId: organizationId ?? 0 };
  const monitor = trpc.incidentResponse.monitor.useQuery(input, { enabled: ready && Boolean(organizationId), refetchInterval: 20_000 });
  const settings = trpc.incidentResponse.settings.get.useQuery(input, { enabled: ready && Boolean(organizationId), retry: false });
  const [agentId, setAgentId] = useState("");
  const [containReason, setContainReason] = useState("");
  const [releaseReason, setReleaseReason] = useState("");
  const [confirmingContainment, setConfirmingContainment] = useState(false);
  const activeAgents = useMemo(() => (monitor.data?.agents ?? []).filter(agent => agent.status === "active"), [monitor.data?.agents]);
  useEffect(() => { if (!agentId && activeAgents[0]) setAgentId(String(activeAgents[0].id)); }, [agentId, activeAgents]);
  const refresh = () => void Promise.all([monitor.refetch(), settings.refetch()]);
  const containment = trpc.incidentResponse.contain.useMutation({ onSuccess: data => { toast.success(data.detail); setContainReason(""); setConfirmingContainment(false); refresh(); }, onError: error => toast.error(error.message) });
  const release = trpc.incidentResponse.release.useMutation({ onSuccess: data => { toast.success(data.detail); setReleaseReason(""); refresh(); }, onError: error => toast.error(error.message) });
  const updateSetting = trpc.incidentResponse.settings.update.useMutation({ onSuccess: () => { toast.success("Automatic containment preference updated with audit evidence."); settings.refetch(); }, onError: error => toast.error(error.message) });

  if (!ready || !organizationId) return <WorkspacePending />;
  const adminControlsAvailable = Boolean(settings.data);
  return <PageFrame eyebrow="Incident response" title="Monitor governed actions. Contain risk on integrated paths." description="Review high-risk actions, governed block decisions, alerts, and agent containment evidence. Emergency containment pauses the registered agent and revokes active runtime credentials; it does not claim visibility or control over direct calls that bypass AgentFence." action={<button className="btn-secondary incident-refresh" onClick={refresh}><RefreshCw size={15} /> Refresh</button>}>
    <section className="incident-summary-grid" aria-label="Incident monitoring summary">
      <article className="console-card incident-summary-card"><Activity size={19} /><span>High-risk actions</span><strong>{monitor.data?.summary.highRiskActions ?? 0}</strong><small>Last 24 hours on integrated paths</small></article>
      <article className="console-card incident-summary-card danger"><ShieldAlert size={19} /><span>Blocked actions</span><strong>{monitor.data?.summary.blockedActions ?? 0}</strong><small>Policy or guardrail decision blocks</small></article>
      <article className="console-card incident-summary-card danger"><Siren size={19} /><span>Active containment</span><strong>{monitor.data?.summary.activeContainments ?? 0}</strong><small>Paused agent workloads</small></article>
      <article className="console-card incident-summary-card"><BellRing size={19} /><span>High-severity alerts</span><strong>{monitor.data?.summary.highSeverityAlerts ?? 0}</strong><small>Privacy-safe operator notifications</small></article>
    </section>

    <section className="incident-grid">
      <article className="console-card incident-panel"><div className="card-heading"><div><p className="card-kicker">Emergency containment</p><h2>Pause a registered agent and revoke active runtime credentials</h2><p className="widget-subtitle">This control stops AgentFence-supported SDK, managed browser-wrapper, and Native MCP Gateway paths for the selected agent. It does not reach direct calls that bypass these integrations.</p></div><PauseCircle size={21} className="text-rose-300" /></div>{adminControlsAvailable ? <><div className="incident-auto-setting"><div><strong>Automatic containment after a critical block</strong><span>{settings.data?.detail}</span></div><button type="button" className={settings.data?.autoContainCriticalBlocks ? "incident-toggle enabled" : "incident-toggle"} disabled={updateSetting.isPending} aria-pressed={settings.data?.autoContainCriticalBlocks ?? false} onClick={() => updateSetting.mutate({ organizationId, autoContainCriticalBlocks: !settings.data?.autoContainCriticalBlocks })}>{settings.data?.autoContainCriticalBlocks ? <ToggleRight size={25} /> : <ToggleLeft size={25} />}<span>{settings.data?.autoContainCriticalBlocks ? "Enabled" : "Disabled"}</span></button></div><div className="incident-containment-form"><label>Registered active agent<select value={agentId} onChange={event => setAgentId(event.target.value)}>{activeAgents.length ? activeAgents.map(agent => <option key={agent.id} value={agent.id}>{agent.name} · {agent.environment} · {agent.riskLevel}</option>) : <option value="">No active agents available</option>}</select></label><label>Containment reason<textarea value={containReason} onChange={event => setContainReason(event.target.value)} maxLength={500} placeholder="Describe the reviewed incident without secrets, tokens, or raw payloads." rows={3} /></label>{confirmingContainment ? <div className="incident-confirm"><CircleAlert size={18} /><div><strong>Confirm emergency containment</strong><span>The agent will be paused and all active runtime credentials will be revoked. New credentials are required after release.</span></div><button className="btn-primary incident-danger-button" disabled={containment.isPending || !agentId || containReason.trim().length < 8} onClick={() => containment.mutate({ organizationId, agentId: Number(agentId), reason: containReason })}>{containment.isPending ? "Containing…" : "Confirm containment"}</button><button className="btn-secondary" disabled={containment.isPending} onClick={() => setConfirmingContainment(false)}>Cancel</button></div> : <button className="btn-primary incident-danger-button" disabled={!agentId || containReason.trim().length < 8} onClick={() => setConfirmingContainment(true)}><Siren size={16} /> Start emergency containment</button>}</div></> : <div className="incident-read-only"><LockKeyhole size={18} /><span>You have monitoring access. Incident containment and automatic-containment settings require an organization administrator.</span></div>}</article>
      <article className="console-card incident-panel"><div className="card-heading"><div><p className="card-kicker">Active containment records</p><h2>Containment state and release workflow</h2><p className="widget-subtitle">Releasing an agent restores its active status only. Revoked runtime credentials are never restored automatically.</p></div><ShieldAlert size={21} className="text-rose-300" /></div><div className="incident-containment-list">{monitor.data?.containments.length ? monitor.data.containments.map(containment => <div className={containment.status === "active" ? "incident-containment-row active" : "incident-containment-row"} key={containment.id}><div><div className="incident-row-title"><strong>{containment.agentName}</strong><Badge tone={containment.status === "active" ? "danger" : "good"}>{containment.status}</Badge></div><span>{containment.trigger.replace(/_/g, " ")} · {containment.reason}</span><small>{new Date(containment.createdAt).toLocaleString()}</small></div>{containment.status === "active" && adminControlsAvailable && <button className="btn-secondary incident-release" disabled={release.isPending || releaseReason.trim().length < 8} onClick={() => release.mutate({ organizationId, containmentId: containment.id, reason: releaseReason })}><PlayCircle size={15} /> Release</button>}</div>) : <p className="incident-empty">No containment records are present for this tenant.</p>}</div>{adminControlsAvailable && Boolean(monitor.data?.containments.some(containment => containment.status === "active")) && <label className="incident-release-reason">Release reason<textarea value={releaseReason} onChange={event => setReleaseReason(event.target.value)} maxLength={500} rows={2} placeholder="Document the review and recovery decision without secrets." /></label>}</article>
    </section>

    <section className="incident-grid incident-grid-secondary">
      <article className="console-card incident-panel"><div className="card-heading"><div><p className="card-kicker">Governed high-risk actions</p><h2>What tools were requested and what happened?</h2><p className="widget-subtitle">Only privacy-safe action metadata is shown: tool, action, destination, sensitivity, risk, decision, and timestamp.</p></div><Activity size={21} className="text-cyan-300" /></div><div className="incident-action-list">{monitor.data?.highRiskActions.length ? monitor.data.highRiskActions.map(action => <div className="incident-action-row" key={action.id}><div><strong>{action.agentName}</strong><span>{action.toolName}.{action.action} → {action.destination}</span><small>{action.dataSensitivity} data · {action.riskLevel} risk · {new Date(action.createdAt).toLocaleString()}</small></div><Badge tone={decisionTone(action.decision)}>{action.decision.replace(/_/g, " ")}</Badge></div>) : <p className="incident-empty">No governed high-risk or blocked actions were recorded in the last 24 hours.</p>}</div></article>
      <article className="console-card incident-panel"><div className="card-heading"><div><p className="card-kicker">High-severity alerts</p><h2>Alert evidence for the incident team</h2><p className="widget-subtitle">Notifications contain safe operational context, not raw requests, secrets, tokens, or target responses.</p></div><BellRing size={21} className="text-amber-300" /></div><div className="incident-alert-list">{monitor.data?.alerts.length ? monitor.data.alerts.map(alert => <div className="incident-alert-row" key={alert.id}><Badge tone={severityTone(alert.severity)}>{alert.severity}</Badge><div><strong>{alert.title}</strong><span>{alert.content}</span><small>{new Date(alert.createdAt).toLocaleString()}</small></div></div>) : <p className="incident-empty">No high-severity alerts were recorded in the last 24 hours.</p>}</div></article>
    </section>
    <p className="incident-boundary"><CircleAlert size={16} /> {monitor.data?.boundary}</p>
  </PageFrame>;
}
