import React, { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, WorkspacePending } from "@/pages/Console";
import { Activity, Archive, ArrowUpRight, Building2, CheckCircle2, CircleAlert, Gauge, KeyRound, Play, RefreshCw, ShieldCheck, SlidersHorizontal, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { EnterprisePilotTour } from "@/components/EnterprisePilotTour";
import "../operations-center.css";

function healthTone(status?: string) { return status === "ready" ? "good" : status === "unhealthy" ? "danger" : status === "pending_activation" ? "warn" : "info"; }
function statusLabel(status?: string) { return status ? status.replace(/_/g, " ") : "not configured"; }

export default function OperationsCenterPage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const [, navigate] = useLocation();
  const utils = trpc.useUtils();
  const queryInput = { organizationId: organizationId ?? 0 };
  const coverage = trpc.coveragePosture.get.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const connections = trpc.enterprise.connections.list.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const vault = trpc.enterprise.connections.vaultActivation.get.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const identity = trpc.enterprise.connections.identityReadiness.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const performance = trpc.governanceOperations.performance.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const readiness = trpc.governanceOperations.pilotReadiness.useQuery(queryInput, { enabled: ready && Boolean(organizationId) });
  const quotas = trpc.governanceOperations.quotas.get.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const schedules = trpc.governanceOperations.evidenceSchedules.list.useQuery(queryInput, { enabled: ready && Boolean(organizationId), refetchInterval: 30_000 });
  const [gatewayQuota, setGatewayQuota] = useState("600");
  const [exportQuota, setExportQuota] = useState("24");
  const [tourOpen, setTourOpen] = useState(false);
  useEffect(() => { if (quotas.data) { setGatewayQuota(String(quotas.data.quotas.gatewayEvaluationsPerMinute)); setExportQuota(String(quotas.data.quotas.evidenceExportsPerDay)); } }, [quotas.data]);
  const refresh = () => void Promise.all([coverage.refetch(), connections.refetch(), vault.refetch(), identity.refetch(), performance.refetch(), readiness.refetch(), quotas.refetch(), schedules.refetch()]);
  const quotaUpdate = trpc.governanceOperations.quotas.update.useMutation({ onSuccess: () => { toast.success("Tenant quotas updated with audit evidence."); quotas.refetch(); }, onError: error => toast.error(error.message) });
  const activateSchedule = trpc.governanceOperations.evidenceSchedules.activate.useMutation({ onSuccess: () => { toast.success("Daily managed-archive export schedule activated."); schedules.refetch(); }, onError: error => toast.error(error.message) });
  const pauseSchedule = trpc.governanceOperations.evidenceSchedules.deactivate.useMutation({ onSuccess: () => { toast.success("Scheduled export paused."); schedules.refetch(); }, onError: error => toast.error(error.message) });
  const runSchedule = trpc.governanceOperations.evidenceSchedules.runNow.useMutation({ onSuccess: data => { toast.success(data.skipped ? `Export skipped: ${data.skipped}` : "Evidence export generated."); schedules.refetch(); }, onError: error => toast.error(error.message) });
  const exportNow = trpc.governanceOperations.evidenceSchedules.exportNow.useMutation({ onSuccess: () => toast.success("Evidence packet generated in managed archive storage."), onError: error => toast.error(error.message) });

  if (!ready || !organizationId) return <WorkspacePending />;
  const connectorCards = [
    ...(connections.data ?? []).map(connection => ({ label: connection.displayName, kind: connection.kind.replace(/_/g, " "), status: connection.status, testedAt: connection.lastTestedAt, code: connection.lastErrorCode, action: () => navigate("/secure-connectors") })),
    { label: "Vault AppRole", kind: "credential boundary", status: vault.data?.connected ? "ready" : vault.data?.endpointConfigured ? "pending_activation" : "not_configured", testedAt: vault.data?.profile?.lastTestedAt ?? null, code: vault.data?.profile?.lastErrorCode ?? null, action: () => navigate("/secure-connectors") },
    { label: "OIDC federation", kind: "identity boundary", status: identity.data?.oidc.ready ? "ready" : identity.data?.oidc.issuerConfigured ? "pending_activation" : "not_configured", testedAt: null, code: identity.data?.oidc.ready ? null : "CUSTOMER_IDP_CONFIGURATION_REQUIRED", action: () => navigate("/secure-connectors") },
  ];
  return <PageFrame eyebrow="Enterprise operations" title="One control plane for every department’s AI agents" description="AgentFence evaluates governed actions in parallel across registered department-owned agents. This view joins coverage evidence, connector health, bounded gateway performance, quota controls, and evidence operations without claiming visibility into direct bypass paths." action={<button className="btn-secondary ops-refresh" onClick={refresh}><RefreshCw size={15} /> Refresh evidence</button>}>
    <section className="ops-hero-grid" aria-label="Organization governance summary">
      <article className="console-card ops-hero-card"><div className="ops-icon"><Building2 size={20} /></div><span>Department teams</span><strong>{coverage.data?.summary.departments ?? 0}</strong><small>Separate owners, shared tenant controls</small></article>
      <article className="console-card ops-hero-card good"><div className="ops-icon"><ShieldCheck size={20} /></div><span>Observed active agents</span><strong>{coverage.data?.summary.observedActiveAgents ?? 0}</strong><small>Evidence in the current 30-day window</small></article>
      <article className="console-card ops-hero-card warn"><div className="ops-icon"><CircleAlert size={20} /></div><span>Coverage gaps</span><strong>{(coverage.data?.summary.policyGaps ?? 0) + (coverage.data?.summary.evidenceGaps ?? 0)}</strong><small>Policy or evidence gaps—not bypass proof</small></article>
      <article className="console-card ops-hero-card"><div className="ops-icon"><Gauge size={20} /></div><span>Policy P95</span><strong>{performance.data?.p95LatencyMs === null || performance.data?.p95LatencyMs === undefined ? "—" : `${performance.data.p95LatencyMs} ms`}</strong><small>{performance.data?.measuredDecisions ?? 0} measured decisions / 24 h</small></article>
    </section>

    <section className="ops-grid">
      <article className="console-card ops-panel ops-departments"><div className="card-heading"><div><p className="card-kicker">Parallel department coverage</p><h2>Governed agent inventory</h2><p className="widget-subtitle">Each registered agent belongs to a department team and is evaluated independently through the same tenant-scoped control plane.</p></div><UsersRound size={21} className="text-cyan-300" /></div><div className="ops-department-table">{coverage.data?.departments.length ? coverage.data.departments.map(department => <div className="ops-department-row" key={department.teamId}><div><strong>{department.departmentName}</strong><span>{department.activeAgents}/{department.registeredAgents} active agents</span></div><span><b>{department.observedActiveAgents}</b> observed</span><span><b>{department.policyGaps}</b> policy gaps</span><span><b>{department.evidenceGaps}</b> evidence gaps</span><span><b>{department.governedActions}</b> governed actions</span></div>) : <p className="ops-empty">Create a team, assign agents, and route their tool actions through AgentFence to establish department-level evidence.</p>}</div><button className="ops-link" onClick={() => navigate("/coverage")}>Open detailed coverage posture <ArrowUpRight size={15} /></button></article>
      <article className="console-card ops-panel"><div className="card-heading"><div><p className="card-kicker">Connector health</p><h2>Safe integration status</h2><p className="widget-subtitle">Statuses and evidence codes only; credential values are never returned.</p></div><KeyRound size={21} className="text-cyan-300" /></div><div className="ops-connector-list">{connectorCards.map((connector, index) => <button className="ops-connector" key={`${connector.label}-${index}`} onClick={connector.action}><div><strong>{connector.label}</strong><span>{connector.kind}</span></div><div className="ops-connector-meta"><Badge tone={healthTone(connector.status)}>{statusLabel(connector.status)}</Badge><small>{connector.code ?? (connector.testedAt ? `Checked ${new Date(connector.testedAt).toLocaleString()}` : "No live evidence yet")}</small></div></button>)}</div><button className="ops-link" onClick={() => navigate("/secure-connectors")}>Manage secure connectors <ArrowUpRight size={15} /></button></article>
    </section>

    <section className="ops-grid ops-grid-secondary">
      <article className="console-card ops-panel"><div className="card-heading"><div><p className="card-kicker">Abuse safeguards</p><h2>Tenant gateway and evidence quotas</h2><p className="widget-subtitle">Quota checks occur before governed action execution and evidence generation. They protect shared capacity without exposing other tenants’ usage.</p></div><SlidersHorizontal size={21} className="text-cyan-300" /></div><div className="ops-usage"><div><span>Gateway evaluations</span><strong>{quotas.data ? `${quotas.data.gatewayEvaluations.used} / ${quotas.data.gatewayEvaluations.limit}` : "—"}</strong><small>Current UTC minute</small></div><div><span>Evidence exports</span><strong>{quotas.data ? `${quotas.data.evidenceExports.used} / ${quotas.data.evidenceExports.limit}` : "—"}</strong><small>Current UTC day</small></div></div><div className="ops-quota-form"><label>Gateway / minute<input value={gatewayQuota} inputMode="numeric" onChange={event => setGatewayQuota(event.target.value)} /></label><label>Exports / day<input value={exportQuota} inputMode="numeric" onChange={event => setExportQuota(event.target.value)} /></label><button className="btn-primary" disabled={quotaUpdate.isPending} onClick={() => quotaUpdate.mutate({ organizationId, gatewayEvaluationsPerMinute: Number(gatewayQuota), evidenceExportsPerDay: Number(exportQuota) })}>Save quotas</button></div></article>
      <article className="console-card ops-panel"><div className="card-heading"><div><p className="card-kicker">Pilot readiness checklist</p><h2>Enterprise rollout gates</h2><p className="widget-subtitle">Turn organization ownership into a reviewable deployment sequence.</p></div><CheckCircle2 size={21} className="text-cyan-300" /></div><div className="ops-checklist">{readiness.data?.items.map(item => <div className={item.complete ? "ops-check complete" : "ops-check"} key={item.key}><CheckCircle2 size={17} /><div><strong>{item.title}</strong><span>{item.detail}</span></div></div>)}</div><button type="button" className="btn-secondary ops-tour-trigger" onClick={() => setTourOpen(true)}>Guide me through setup <ArrowUpRight size={15} /></button><p className="ops-boundary">{readiness.data?.boundary}</p></article>
    </section>

    <section className="ops-grid ops-grid-secondary">
      <article className="console-card ops-panel"><div className="card-heading"><div><p className="card-kicker">Measured enforcement performance</p><h2>Policy decision evidence</h2><p className="widget-subtitle">Measured only at AgentFence’s decision point; this excludes model, network, approval, and target execution time.</p></div><Activity size={21} className="text-cyan-300" /></div><div className="ops-usage"><div><span>Average</span><strong>{performance.data?.averageLatencyMs === null || performance.data?.averageLatencyMs === undefined ? "—" : `${performance.data.averageLatencyMs} ms`}</strong><small>Integrated decision path</small></div><div><span>Maximum</span><strong>{performance.data?.maxLatencyMs === null || performance.data?.maxLatencyMs === undefined ? "—" : `${performance.data.maxLatencyMs} ms`}</strong><small>{performance.data?.unmeasuredLegacyDecisions ?? 0} legacy rows excluded</small></div></div><p className="ops-boundary">{performance.data?.detail}</p></article>
      <article className="console-card ops-panel"><div className="card-heading"><div><p className="card-kicker">Audit evidence automation</p><h2>Managed archive exports</h2><p className="widget-subtitle">Manual evidence exports are available now. Daily automation activates only after production publication and runs at 02:00 UTC.</p></div><Archive size={21} className="text-cyan-300" /></div><div className="ops-export-actions">{["SOC 2", "ISO 27001", "insurance review"].map(value => <button key={value} className="btn-secondary" disabled={exportNow.isPending} onClick={() => exportNow.mutate({ organizationId, framework: value as "SOC 2" | "ISO 27001" | "insurance review" })}>Export {value}</button>)}</div><div className="ops-schedule-list">{schedules.data?.map(schedule => <div className="ops-schedule" key={schedule.id}><div><strong>{schedule.framework}</strong><span>{schedule.lastRunCode ?? "No run evidence yet"}</span></div><Badge tone={healthTone(schedule.status === "active" ? "ready" : schedule.status)}>{statusLabel(schedule.status)}</Badge><div className="ops-schedule-actions"><button aria-label={`Run ${schedule.framework} schedule now`} onClick={() => runSchedule.mutate({ organizationId, scheduleId: schedule.id })}><Play size={14} /></button><button aria-label={`Pause ${schedule.framework} schedule`} onClick={() => pauseSchedule.mutate({ organizationId, scheduleId: schedule.id })}>Pause</button></div></div>)}</div><div className="ops-export-actions">{["SOC 2", "ISO 27001", "insurance review"].map(value => <button key={`schedule-${value}`} className="btn-primary" disabled={activateSchedule.isPending} onClick={() => activateSchedule.mutate({ organizationId, framework: value as "SOC 2" | "ISO 27001" | "insurance review", deliveryMode: "managed_archive" })}>Schedule {value}</button>)}</div><p className="ops-boundary">Customer-owned S3 or WORM storage remains an activation boundary until a tenant-owned storage connector and least-privilege credentials are certified. No storage secrets are accepted here.</p></article>
    </section>

    <section className="console-card ops-language-boundary"><ShieldCheck size={20} /><div><p className="card-kicker">Enforcement boundary</p><h2>Action governance is deterministic; language safety is complementary.</h2><p>AgentFence governs a requested tool action only after the integrated SDK, browser wrapper, or Native MCP gateway supplies a structured request. Natural-language prompts can be ambiguous or malicious, so organizations should combine model-side prompt defenses and constrained tool schemas with AgentFence’s identity, policy, Data Guard, approval, quota, and audit controls. The decisive stop occurs before a governed external action is executed—not by attempting to prove that all language is safe.</p></div><button className="ops-link" onClick={() => navigate("/policy-governance")}>Review policy diffs <ArrowUpRight size={15} /></button></section>
    <EnterprisePilotTour open={tourOpen} onClose={() => setTourOpen(false)} onNavigate={navigate} />
  </PageFrame>;
}
