import React, { FormEvent, useEffect, useState } from "react";
import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, WorkspacePending } from "@/pages/Console";
import { CheckCircle2, CircleAlert, ClipboardCheck, Loader2, ShieldCheck, TimerReset } from "lucide-react";
import { toast } from "sonner";
import "../operational-readiness.css";

function tone(status: string | null | undefined) { return status === "exercise_recorded" || status === "passed" ? "good" : status === "needs_remediation" || status === "failed" ? "danger" : "warn"; }
function percent(bps: number | undefined) { return bps === undefined ? "—" : `${(bps / 100).toFixed(2)}%`; }

export default function OperationalReadinessPage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const utils = trpc.useUtils();
  const readiness = trpc.operationalReadiness.get.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const [form, setForm] = useState({ ownerName: "", backupProvider: "", backupEvidenceReference: "", runbookReference: "", rtoMinutes: 240, rpoMinutes: 60, availabilitySloBasisPoints: 9990 });
  const [exercise, setExercise] = useState({ outcome: "passed" as "passed" | "failed" | "partial", evidenceReference: "", notes: "" });
  useEffect(() => { const profile = readiness.data?.profile; if (profile) setForm({ ownerName: profile.ownerName, backupProvider: profile.backupProvider, backupEvidenceReference: profile.backupEvidenceReference ?? "", runbookReference: profile.runbookReference ?? "", rtoMinutes: profile.rtoMinutes, rpoMinutes: profile.rpoMinutes, availabilitySloBasisPoints: profile.availabilitySloBasisPoints }); }, [readiness.data?.profile]);
  const refresh = () => utils.operationalReadiness.get.invalidate();
  const declare = trpc.operationalReadiness.declare.useMutation({ onSuccess: () => { toast.success("Resilience targets recorded as customer-declared operational objectives."); refresh(); }, onError: error => toast.error(error.message) });
  const recordExercise = trpc.operationalReadiness.recordExercise.useMutation({ onSuccess: result => { toast[result.status === "exercise_recorded" ? "success" : "warning"]("Customer-led exercise evidence recorded."); setExercise({ outcome: "passed", evidenceReference: "", notes: "" }); refresh(); }, onError: error => toast.error(error.message) });
  if (!ready || !organizationId) return <WorkspacePending />;
  return <PageFrame eyebrow="Operational readiness" title="Declare recovery objectives. Prove them with customer-led exercises." description="This workspace records intended service objectives and customer-reported recovery exercise evidence. It does not create a backup, perform a restore, or claim that OIDC or SCIM is live." action={<Badge tone={tone(readiness.data?.profile?.status)}>{readiness.data?.profile?.status?.replace(/_/g, " ") ?? "Not declared"}</Badge>}>
    <section className="readiness-boundary"><CircleAlert size={19} /><div><strong>Evidence is not execution</strong><span>RTO, RPO, SLO, backup-provider, and runbook fields document customer decisions. A recorded exercise must be supported by customer-controlled recovery evidence; AgentFence does not independently verify the provider-side backup or restore.</span></div></section>
    <section className="readiness-grid"><form className="console-card readiness-form" onSubmit={(event: FormEvent) => { event.preventDefault(); declare.mutate({ organizationId, ...form, backupEvidenceReference: form.backupEvidenceReference || undefined, runbookReference: form.runbookReference || undefined }); }}><div className="card-heading"><div><p className="card-kicker">Step 1 · declared targets</p><h2>Service and recovery objectives</h2><p className="widget-subtitle">Set targets only after the accountable owner and hosting provider agree they are feasible and measurable.</p></div><TimerReset size={21} className="text-cyan-300" /></div><div className="form-grid"><label className="field-wrap"><span className="field-label">Accountable owner</span><input required value={form.ownerName} onChange={event => setForm({ ...form, ownerName: event.target.value })} placeholder="Platform operations owner" /></label><label className="field-wrap"><span className="field-label">Backup or recovery provider</span><input required value={form.backupProvider} onChange={event => setForm({ ...form, backupProvider: event.target.value })} placeholder="Customer cloud backup service" /></label><label className="field-wrap"><span className="field-label">RTO (minutes)</span><input required type="number" min={1} max={525600} value={form.rtoMinutes} onChange={event => setForm({ ...form, rtoMinutes: Number(event.target.value) })} /></label><label className="field-wrap"><span className="field-label">RPO (minutes)</span><input required type="number" min={1} max={525600} value={form.rpoMinutes} onChange={event => setForm({ ...form, rpoMinutes: Number(event.target.value) })} /></label><label className="field-wrap"><span className="field-label">Availability SLO (basis points)</span><input required type="number" min={9000} max={10000} value={form.availabilitySloBasisPoints} onChange={event => setForm({ ...form, availabilitySloBasisPoints: Number(event.target.value) })} /><span className="field-hint">{percent(form.availabilitySloBasisPoints)} target. This is an objective, not an SLA.</span></label><label className="field-wrap"><span className="field-label">Backup evidence reference</span><input value={form.backupEvidenceReference} onChange={event => setForm({ ...form, backupEvidenceReference: event.target.value })} placeholder="Customer ticket, bucket inventory, or report ID" /></label></div><label className="field-wrap"><span className="field-label">Recovery runbook reference</span><input value={form.runbookReference} onChange={event => setForm({ ...form, runbookReference: event.target.value })} placeholder="Customer runbook location or approved document ID" /><span className="field-hint">Do not enter a token, password, signed URL, or credential-bearing link.</span></label><button className="btn-primary" disabled={declare.isPending}>{declare.isPending ? <Loader2 className="animate-spin" size={16} /> : <ClipboardCheck size={16} />} Record declared objectives</button></form>
      <form className="console-card readiness-form" onSubmit={(event: FormEvent) => { event.preventDefault(); recordExercise.mutate({ organizationId, ...exercise }); }}><div className="card-heading"><div><p className="card-kicker">Step 2 · customer-led recovery exercise</p><h2>Record test evidence</h2><p className="widget-subtitle">Record the outcome only after the customer has executed the referenced runbook, evaluated access controls, and retained proof in their own evidence system.</p></div><CheckCircle2 size={21} className="text-emerald-300" /></div><label className="field-wrap"><span className="field-label">Exercise outcome</span><select value={exercise.outcome} onChange={event => setExercise({ ...exercise, outcome: event.target.value as typeof exercise.outcome })}><option value="passed">Passed</option><option value="partial">Partial</option><option value="failed">Failed</option></select></label><label className="field-wrap"><span className="field-label">Customer evidence reference</span><input required value={exercise.evidenceReference} onChange={event => setExercise({ ...exercise, evidenceReference: event.target.value })} placeholder="Customer DR exercise ticket or report ID" /></label><label className="field-wrap"><span className="field-label">Outcome notes</span><textarea required minLength={10} value={exercise.notes} onChange={event => setExercise({ ...exercise, notes: event.target.value })} placeholder="Summarize scope, observed RTO/RPO, identity-access checks, and remediation without including secrets." /></label><button className="btn-primary" disabled={!readiness.data?.profile || recordExercise.isPending}>{recordExercise.isPending ? <Loader2 className="animate-spin" size={16} /> : <ShieldCheck size={16} />} Record exercise evidence</button>{!readiness.data?.profile && <p className="readiness-form-note">Declare objectives before recording an exercise.</p>}</form></section>
    <section className="readiness-status-grid"><article className="console-card readiness-status"><p className="card-kicker">Declared posture</p><h2>{readiness.data?.profile ? `${percent(readiness.data.profile.availabilitySloBasisPoints)} availability objective` : "No targets declared"}</h2><dl><div><dt>RTO</dt><dd>{readiness.data?.profile ? `${readiness.data.profile.rtoMinutes} minutes` : "—"}</dd></div><div><dt>RPO</dt><dd>{readiness.data?.profile ? `${readiness.data.profile.rpoMinutes} minutes` : "—"}</dd></div><div><dt>Owner</dt><dd>{readiness.data?.profile?.ownerName ?? "—"}</dd></div><div><dt>Backup provider</dt><dd>{readiness.data?.profile?.backupProvider ?? "—"}</dd></div></dl></article><article className="console-card readiness-status"><p className="card-kicker">Latest customer exercise</p><h2>{readiness.data?.profile?.lastExerciseOutcome?.replace(/_/g, " ") ?? "Not recorded"}</h2><dl><div><dt>Recorded at</dt><dd>{readiness.data?.profile?.lastExerciseAt ? new Date(readiness.data.profile.lastExerciseAt).toLocaleString() : "—"}</dd></div><div><dt>Evidence</dt><dd>{readiness.data?.profile?.lastExerciseEvidenceReference ?? "—"}</dd></div><div><dt>Notes</dt><dd>{readiness.data?.profile?.lastExerciseNotes ?? "—"}</dd></div></dl></article><article className="console-card readiness-status"><p className="card-kicker">Identity activation boundary</p><h2>Readiness is not live identity</h2><div className="identity-readiness-checks"><span className={readiness.data?.identity.oidc.issuerConfigured ? "ready" : ""}><i /> OIDC issuer</span><span className={readiness.data?.identity.oidc.clientIdConfigured ? "ready" : ""}><i /> OIDC client ID</span><span className={readiness.data?.identity.oidc.clientSecretConfigured ? "ready" : ""}><i /> OIDC client secret</span><span className={readiness.data?.identity.scim.baseUrlConfigured ? "ready" : ""}><i /> SCIM base URL</span><span className={readiness.data?.identity.scim.bearerTokenConfigured ? "ready" : ""}><i /> SCIM bearer token</span></div><p>{readiness.data?.identity.boundary}</p></article></section>
  </PageFrame>;
}
