import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, SecondaryButton, WorkspacePending } from "@/pages/Console";
import { CheckCircle2, CircleAlert, KeyRound, Loader2, Network, Send, ShieldCheck, TestTube2 } from "lucide-react";
import React, { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import "../secure-connectors.css";

const credentialLikeKey = /(secret|token|password|api[_-]?key|routing[_-]?key)/i;
function statusTone(status: string | undefined) { return status === "ready" || status === "certified" ? "good" : status === "unhealthy" || status === "failed" ? "danger" : "warn"; }

export default function SecureConnectorSettingsPage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const utils = trpc.useUtils();
  const connections = trpc.enterprise.connections.list.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const vault = trpc.agentfence.vault.status.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const identity = trpc.enterprise.connections.identityReadiness.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const splunk = useMemo(() => (connections.data ?? []).find(connection => connection.kind === "splunk_hec") ?? null, [connections.data]);
  const [form, setForm] = useState({ displayName: "Splunk HEC", endpoint: "", vaultSecretPath: "", metadataKey: "index", metadataValue: "agentfence_audit" });
  const refresh = () => Promise.all([utils.enterprise.connections.list.invalidate(), utils.enterprise.connections.identityReadiness.invalidate(), utils.agentfence.vault.status.invalidate()]);
  const save = trpc.enterprise.connections.save.useMutation({ onSuccess: () => { toast.success("Splunk profile saved without storing a raw credential."); refresh(); }, onError: error => toast.error(error.message) });
  const test = trpc.enterprise.connections.test.useMutation({ onSuccess: result => { toast.success(result.detail); refresh(); }, onError: error => toast.error(error.message) });
  const certify = trpc.enterprise.connections.certifySplunkHec.useMutation({ onSuccess: result => { toast[result.certified ? "success" : "warning"](`Certification result: ${result.evidenceCode.replace(/_/g, " ")}.`); refresh(); }, onError: error => toast.error(error.message) });
  if (!ready || !organizationId) return <WorkspacePending />;
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (credentialLikeKey.test(form.metadataKey)) return toast.error("Metadata keys cannot resemble credentials. Use Vault for all secret material.");
    save.mutate({ organizationId, kind: "splunk_hec", displayName: form.displayName, endpoint: form.endpoint || undefined, vaultSecretPath: form.vaultSecretPath || undefined, safeConfig: form.metadataKey && form.metadataValue ? { [form.metadataKey]: form.metadataValue } : undefined });
  };
  return <PageFrame eyebrow="Secure connector settings" title="Activate integrations without browser-held secrets" description="Configure only HTTPS endpoints, safe metadata, and tenant-scoped Vault references. AgentFence evaluates credentials server-side only during controlled connector certification." action={<Badge tone="info">No raw credential entry</Badge>}>
    <section className="connector-boundary" aria-label="Secure connector boundary"><div><KeyRound size={18} /><div><strong>Credential boundary</strong><span>Vault path reference → server-only read → controlled delivery probe → audit evidence. The browser never receives the provider secret.</span></div></div><Badge tone={vault.data?.connected ? "good" : "warn"}>{vault.data?.connected ? "Vault AppRole ready" : "Vault activation required"}</Badge></section>
    <section className="connector-activation-grid">
      <form className="console-card connector-form" onSubmit={submit}><div className="card-heading"><div><p className="card-kicker">Certified SIEM workflow</p><h2>Splunk HEC profile</h2><p className="widget-subtitle">Only a metadata-safe profile is persisted. Place the HEC token in the organization’s approved customer Vault path.</p></div><Network size={20} className="text-cyan-300" /></div><label className="field-wrap"><span className="field-label">Profile name</span><input required value={form.displayName} onChange={event => setForm({ ...form, displayName: event.target.value })} /></label><label className="field-wrap"><span className="field-label">HEC endpoint</span><input required type="url" value={form.endpoint} onChange={event => setForm({ ...form, endpoint: event.target.value })} placeholder="https://splunk.example.com:8088/services/collector/event" /><span className="field-hint">HTTPS is mandatory. Use a specific customer-owned HTTP Event Collector endpoint.</span></label><label className="field-wrap"><span className="field-label">Tenant Vault secret reference</span><input required value={form.vaultSecretPath} onChange={event => setForm({ ...form, vaultSecretPath: event.target.value })} placeholder={`agentfence/tenants/${organizationId}/integrations/splunk_hec/hec-token`} /><span className="field-hint">The Vault secret record must contain only a server-read <code>hec_token</code> or <code>token</code> value. Do not paste it here.</span></label><div className="form-grid"><label className="field-wrap"><span className="field-label">Safe metadata key</span><input value={form.metadataKey} onChange={event => setForm({ ...form, metadataKey: event.target.value })} placeholder="index" /></label><label className="field-wrap"><span className="field-label">Safe metadata value</span><input value={form.metadataValue} onChange={event => setForm({ ...form, metadataValue: event.target.value })} placeholder="agentfence_audit" /></label></div><button className="btn-primary" disabled={save.isPending}>{save.isPending ? <Loader2 className="animate-spin" size={16} /> : <Send size={16} />} Save secure profile</button></form>
      <article className="console-card connector-certification"><div className="card-heading"><div><p className="card-kicker">Live certification evidence</p><h2>Verify controlled HEC delivery</h2></div><Badge tone={statusTone(splunk?.status)}>{splunk?.status?.replace(/_/g, " ") ?? "not configured"}</Badge></div><p>A certification sends one bounded AgentFence certification event using the Vault-held HEC token. No raw secret or response body is stored or displayed.</p><dl className="connector-facts"><div><dt>Endpoint</dt><dd>{splunk?.endpoint ?? "Not configured"}</dd></div><div><dt>Vault reference</dt><dd>{splunk?.hasVaultReference ? "Configured" : "Required"}</dd></div><div><dt>Last evidence</dt><dd>{splunk?.lastErrorCode ? splunk.lastErrorCode.replace(/_/g, " ") : splunk?.lastTestedAt ? `Tested ${new Date(splunk.lastTestedAt).toLocaleString()}` : "Not tested"}</dd></div></dl><div className="connector-certification-actions"><SecondaryButton type="button" disabled={!splunk || test.isPending} onClick={() => test.mutate({ organizationId, kind: "splunk_hec" })}><TestTube2 size={15} /> Preflight profile</SecondaryButton><button type="button" className="btn-primary" disabled={!splunk || certify.isPending} onClick={() => splunk && certify.mutate({ organizationId, connectionId: splunk.id })}>{certify.isPending ? <Loader2 className="animate-spin" size={15} /> : <CheckCircle2 size={15} />} Certify Splunk HEC</button></div><div className="connector-certification-note"><CircleAlert size={15} /><span>{vault.data?.connected ? "AppRole appears configured. Certification still requires a valid customer Vault reference and reachable HEC endpoint." : "Certification remains activation-required until customer Vault AppRole credentials are supplied in secure deployment settings."}</span></div></article>
    </section>
    <section className="connector-readiness-grid"><article className="console-card connector-readiness"><div className="card-heading"><div><p className="card-kicker">Deployment-only identity readiness</p><h2>OIDC federation</h2></div><Badge tone={identity.data?.oidc.ready ? "good" : "warn"}>{identity.data?.oidc.ready ? "Ready" : "Activation required"}</Badge></div><div className="readiness-checks"><span className={identity.data?.oidc.issuerConfigured ? "ready" : ""}><i /> Issuer URL</span><span className={identity.data?.oidc.clientIdConfigured ? "ready" : ""}><i /> Client ID</span><span className={identity.data?.oidc.clientSecretConfigured ? "ready" : ""}><i /> Client secret</span></div><p>Configure these deployment values through protected project settings. Values are never rendered, persisted in connector metadata, or logged.</p></article><article className="console-card connector-readiness"><div className="card-heading"><div><p className="card-kicker">Lifecycle provisioning readiness</p><h2>SCIM 2.0</h2></div><Badge tone={identity.data?.scim.ready ? "good" : "warn"}>{identity.data?.scim.ready ? "Ready" : "Activation required"}</Badge></div><div className="readiness-checks"><span className={identity.data?.scim.baseUrlConfigured ? "ready" : ""}><i /> SCIM base URL</span><span className={identity.data?.scim.bearerTokenConfigured ? "ready" : ""}><i /> Bearer token</span></div><p>SCIM credentials stay in secure deployment configuration. This state provides only a Boolean readiness signal for administrators.</p></article><article className="console-card connector-readiness"><div className="card-heading"><div><p className="card-kicker">Vault prerequisite</p><h2>AppRole status</h2></div><Badge tone={vault.data?.connected ? "good" : "warn"}>{vault.data?.connected ? "Connected" : "Disconnected-safe"}</Badge></div><div className="readiness-checks"><span className={vault.data?.endpointConfigured ? "ready" : ""}><i /> VAULT_ADDR</span><span className={vault.data?.roleIdConfigured ? "ready" : ""}><i /> VAULT_ROLE_ID</span><span className={vault.data?.secretIdConfigured ? "ready" : ""}><i /> VAULT_SECRET_ID</span></div><p>All three values are customer-controlled deployment secrets. AgentFence exposes status only and does not accept credentials in this UI.</p></article></section>
  </PageFrame>;
}
