import { useAgentFenceWorkspace } from "@/contexts/AgentFenceContext";
import { trpc } from "@/lib/trpc";
import { Badge, PageFrame, SecondaryButton, WorkspacePending } from "@/pages/Console";
import { Activity, CheckCircle2, CircleAlert, KeyRound, Loader2, Network, PauseCircle, PlayCircle, RefreshCw, Send, ShieldCheck, TestTube2 } from "lucide-react";
import React, { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import "../secure-connectors.css";

const credentialLikeKey = /(secret|token|password|api[_-]?key|routing[_-]?key)/i;
function statusTone(status: string | undefined) { return status === "ready" || status === "certified" ? "good" : status === "unhealthy" || status === "failed" ? "danger" : "warn"; }

export default function SecureConnectorSettingsPage() {
  const { organizationId, ready } = useAgentFenceWorkspace();
  const utils = trpc.useUtils();
  const connections = trpc.enterprise.connections.list.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const vault = trpc.agentfence.vault.status.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const identity = trpc.enterprise.connections.identityReadiness.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const vaultActivation = trpc.enterprise.connections.vaultActivation.get.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const siemDelivery = trpc.siemDelivery.get.useQuery({ organizationId: organizationId ?? 0 }, { enabled: ready && Boolean(organizationId) });
  const splunk = useMemo(() => (connections.data ?? []).find(connection => connection.kind === "splunk_hec") ?? null, [connections.data]);
  const [form, setForm] = useState({ displayName: "Splunk HEC", endpoint: "", vaultSecretPath: "", metadataKey: "index", metadataValue: "agentfence_audit" });
  const [vaultForm, setVaultForm] = useState({ displayName: "Customer Vault AppRole", endpoint: "" });
  const refresh = () => Promise.all([utils.enterprise.connections.list.invalidate(), utils.enterprise.connections.identityReadiness.invalidate(), utils.enterprise.connections.vaultActivation.get.invalidate(), utils.agentfence.vault.status.invalidate(), utils.siemDelivery.get.invalidate()]);
  const save = trpc.enterprise.connections.save.useMutation({ onSuccess: () => { toast.success("Splunk profile saved without storing a raw credential."); refresh(); }, onError: error => toast.error(error.message) });
  const test = trpc.enterprise.connections.test.useMutation({ onSuccess: result => { toast.success(result.detail); refresh(); }, onError: error => toast.error(error.message) });
  const certify = trpc.enterprise.connections.certifySplunkHec.useMutation({ onSuccess: result => { toast[result.certified ? "success" : "warning"](`Certification result: ${result.evidenceCode.replace(/_/g, " ")}.`); refresh(); }, onError: error => toast.error(error.message) });
  const activateVault = trpc.enterprise.connections.vaultActivation.activate.useMutation({ onSuccess: result => { toast[result.ready ? "success" : "warning"](result.detail); refresh(); }, onError: error => toast.error(error.message) });
  const activateDelivery = trpc.siemDelivery.activate.useMutation({ onSuccess: () => { toast.success("Continuous Splunk delivery schedule activated. Each delivery uses a privacy-safe audit envelope."); refresh(); }, onError: error => toast.error(error.message) });
  const pauseDelivery = trpc.siemDelivery.deactivate.useMutation({ onSuccess: () => { toast.success("Continuous Splunk delivery is paused."); refresh(); }, onError: error => toast.error(error.message) });
  const flushDelivery = trpc.siemDelivery.flushNow.useMutation({ onSuccess: result => { toast.success(`Delivery flush: ${result.delivery.delivered} delivered, ${result.delivery.retrying} retrying, ${result.delivery.failed} failed.`); refresh(); }, onError: error => toast.error(error.message) });
  if (!ready || !organizationId) return <WorkspacePending />;
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (credentialLikeKey.test(form.metadataKey)) return toast.error("Metadata keys cannot resemble credentials. Use Vault for all secret material.");
    save.mutate({ organizationId, kind: "splunk_hec", displayName: form.displayName, endpoint: form.endpoint || undefined, vaultSecretPath: form.vaultSecretPath || undefined, safeConfig: form.metadataKey && form.metadataValue ? { [form.metadataKey]: form.metadataValue } : undefined });
  };
  return <PageFrame eyebrow="Secure connector settings" title="Activate integrations without browser-held secrets" description="Configure only HTTPS endpoints, safe metadata, and tenant-scoped Vault references. AgentFence evaluates credentials server-side only during controlled connector certification." action={<Badge tone="info">No raw credential entry</Badge>}>
    <section className="connector-boundary" aria-label="Secure connector boundary"><div><KeyRound size={18} /><div><strong>Credential boundary</strong><span>Vault path reference → server-only read → controlled delivery probe → audit evidence. The browser never receives the provider secret.</span></div></div><Badge tone={vault.data?.connected ? "good" : "warn"}>{vault.data?.connected ? "Vault AppRole ready" : "Vault activation required"}</Badge></section>
    <section className="connector-activation-grid">
      <form className="console-card connector-form" onSubmit={submit}><div className="card-heading"><div><p className="card-kicker">Certified SIEM workflow</p><h2>Splunk HEC profile</h2><p className="widget-subtitle">Only a metadata-safe profile is persisted. Place the HEC token in the organization’s approved customer Vault path.</p></div><Network size={20} className="text-cyan-300" /></div><label className="field-wrap"><span className="field-label">Profile name</span><input required value={form.displayName} onChange={event => setForm({ ...form, displayName: event.target.value })} /></label><label className="field-wrap"><span className="field-label">HEC endpoint</span><input required type="url" value={form.endpoint} onChange={event => setForm({ ...form, endpoint: event.target.value })} placeholder="https://splunk.example.com:8088/services/collector/event" /><span className="field-hint">HTTPS is mandatory. Use a specific customer-owned HTTP Event Collector endpoint.</span></label><label className="field-wrap"><span className="field-label">Tenant Vault secret reference</span><input required value={form.vaultSecretPath} onChange={event => setForm({ ...form, vaultSecretPath: event.target.value })} placeholder={`agentfence/tenants/${organizationId}/integrations/splunk_hec/hec-token`} /><span className="field-hint">The Vault secret record must contain only a server-read <code>hec_token</code> or <code>token</code> value. Do not paste it here.</span></label><div className="form-grid"><label className="field-wrap"><span className="field-label">Safe metadata key</span><input value={form.metadataKey} onChange={event => setForm({ ...form, metadataKey: event.target.value })} placeholder="index" /></label><label className="field-wrap"><span className="field-label">Safe metadata value</span><input value={form.metadataValue} onChange={event => setForm({ ...form, metadataValue: event.target.value })} placeholder="agentfence_audit" /></label></div><button className="btn-primary" disabled={save.isPending}>{save.isPending ? <Loader2 className="animate-spin" size={16} /> : <Send size={16} />} Save secure profile</button></form>
      <article className="console-card connector-certification"><div className="card-heading"><div><p className="card-kicker">Live certification evidence</p><h2>Verify controlled HEC delivery</h2></div><Badge tone={statusTone(splunk?.status)}>{splunk?.status?.replace(/_/g, " ") ?? "not configured"}</Badge></div><p>A certification sends one bounded AgentFence certification event using the Vault-held HEC token. No raw secret or response body is stored or displayed.</p><dl className="connector-facts"><div><dt>Endpoint</dt><dd>{splunk?.endpoint ?? "Not configured"}</dd></div><div><dt>Vault reference</dt><dd>{splunk?.hasVaultReference ? "Configured" : "Required"}</dd></div><div><dt>Last evidence</dt><dd>{splunk?.lastErrorCode ? splunk.lastErrorCode.replace(/_/g, " ") : splunk?.lastTestedAt ? `Tested ${new Date(splunk.lastTestedAt).toLocaleString()}` : "Not tested"}</dd></div></dl><div className="connector-certification-actions"><SecondaryButton type="button" disabled={!splunk || test.isPending} onClick={() => test.mutate({ organizationId, kind: "splunk_hec" })}><TestTube2 size={15} /> Preflight profile</SecondaryButton><button type="button" className="btn-primary" disabled={!splunk || certify.isPending} onClick={() => splunk && certify.mutate({ organizationId, connectionId: splunk.id })}>{certify.isPending ? <Loader2 className="animate-spin" size={15} /> : <CheckCircle2 size={15} />} Certify Splunk HEC</button></div><div className="connector-certification-note"><CircleAlert size={15} /><span>{vault.data?.connected ? "AppRole appears configured. Certification still requires a valid customer Vault reference and reachable HEC endpoint." : "Certification remains activation-required until customer Vault AppRole credentials are supplied in secure deployment settings."}</span></div></article>
    </section>
    <section className="connector-activation-grid connector-vault-activation"><form className="console-card connector-form" onSubmit={event => { event.preventDefault(); activateVault.mutate({ organizationId, ...vaultForm }); }}><div className="card-heading"><div><p className="card-kicker">Customer-controlled activation</p><h2>Activate Vault AppRole</h2><p className="widget-subtitle">Provide only the HTTPS address. Role ID and Secret ID are protected deployment values and are never accepted by this UI.</p></div><KeyRound size={20} className="text-cyan-300" /></div><label className="field-wrap"><span className="field-label">Vault profile name</span><input required value={vaultForm.displayName} onChange={event => setVaultForm({ ...vaultForm, displayName: event.target.value })} /></label><label className="field-wrap"><span className="field-label">Customer Vault HTTPS address</span><input required type="url" value={vaultForm.endpoint} onChange={event => setVaultForm({ ...vaultForm, endpoint: event.target.value })} placeholder="https://vault.customer.example" /><span className="field-hint">Must exactly match the protected deployment Vault address when activation runs.</span></label><button className="btn-primary" disabled={activateVault.isPending}>{activateVault.isPending ? <Loader2 className="animate-spin" size={16} /> : <ShieldCheck size={16} />} Authenticate AppRole</button></form><article className="console-card connector-certification"><div className="card-heading"><div><p className="card-kicker">Deployment-only vault readiness</p><h2>AppRole activation evidence</h2></div><Badge tone={vaultActivation.data?.profile?.status === "ready" ? "good" : "warn"}>{vaultActivation.data?.profile?.status?.replace(/_/g, " ") ?? "not activated"}</Badge></div><div className="readiness-checks"><span className={vaultActivation.data?.endpointConfigured ? "ready" : ""}><i /> VAULT_ADDR</span><span className={vaultActivation.data?.roleIdConfigured ? "ready" : ""}><i /> VAULT_ROLE_ID</span><span className={vaultActivation.data?.secretIdConfigured ? "ready" : ""}><i /> VAULT_SECRET_ID</span></div><p>{vaultActivation.data?.detail}</p><dl className="connector-facts"><div><dt>Configured endpoint</dt><dd>{vaultActivation.data?.profile?.endpoint ?? "Not yet saved"}</dd></div><div><dt>Latest evidence</dt><dd>{vaultActivation.data?.profile?.lastErrorCode?.replace(/_/g, " ") ?? (vaultActivation.data?.connected ? "Awaiting activation check" : "Deployment secrets required")}</dd></div></dl></article></section>
    <section className="console-card siem-delivery-panel" aria-label="Continuous Splunk delivery"><div className="card-heading"><div><p className="card-kicker">Durable SIEM delivery</p><h2>Continuous privacy-safe audit delivery</h2><p className="widget-subtitle">AgentFence queues a redacted audit envelope, retries bounded failures, records delivery state, and uses a platform-managed Heartbeat schedule only after the HEC profile is certified.</p></div><Badge tone={siemDelivery.data?.settings?.enabled ? "good" : "warn"}>{siemDelivery.data?.settings?.enabled ? "Scheduled" : "Inactive"}</Badge></div><div className="siem-delivery-facts"><span><strong>Connector</strong>{siemDelivery.data?.connection?.status === "ready" ? "Certified HEC ready" : "Certification required"}</span><span><strong>Outbox</strong>{siemDelivery.data?.settings ? `${siemDelivery.data.settings.counts.queued} queued · ${siemDelivery.data.settings.counts.retrying} retrying · ${siemDelivery.data.settings.counts.failed} failed` : "Not initialized"}</span><span><strong>Last delivery</strong>{siemDelivery.data?.settings?.lastDeliveryCode?.replace(/_/g, " ") ?? "No delivery attempt"}</span></div><div className="siem-delivery-actions">{siemDelivery.data?.settings?.enabled ? <SecondaryButton type="button" disabled={pauseDelivery.isPending} onClick={() => pauseDelivery.mutate({ organizationId })}>{pauseDelivery.isPending ? <Loader2 className="animate-spin" size={15} /> : <PauseCircle size={15} />} Pause delivery</SecondaryButton> : <button type="button" className="btn-primary" disabled={!siemDelivery.data?.connection || siemDelivery.data.connection.status !== "ready" || activateDelivery.isPending} onClick={() => siemDelivery.data?.connection && activateDelivery.mutate({ organizationId, connectionId: siemDelivery.data.connection.id })}>{activateDelivery.isPending ? <Loader2 className="animate-spin" size={15} /> : <PlayCircle size={15} />} Activate continuous delivery</button>}<SecondaryButton type="button" disabled={!siemDelivery.data?.settings?.enabled || flushDelivery.isPending} onClick={() => flushDelivery.mutate({ organizationId })}>{flushDelivery.isPending ? <Loader2 className="animate-spin" size={15} /> : <RefreshCw size={15} />} Flush due events</SecondaryButton></div><div className="siem-delivery-note"><CircleAlert size={15} /><span>Activation is production-only because the schedule calls the deployed site. This delivery path forwards no actor email, raw audit payload, token, or credential. Successful certification is required but does not by itself imply continuous delivery.</span></div>{(siemDelivery.data?.recent ?? []).length > 0 && <div className="siem-delivery-history">{siemDelivery.data?.recent.map(item => <span key={item.id}><Activity size={13} /> #{item.id} {item.status} · attempt {item.attempts} · {item.lastDeliveryCode?.replace(/_/g, " ") ?? "pending"}</span>)}</div>}</section>
    <section className="connector-readiness-grid"><article className="console-card connector-readiness"><div className="card-heading"><div><p className="card-kicker">Deployment-only identity readiness</p><h2>OIDC federation</h2></div><Badge tone={identity.data?.oidc.ready ? "good" : "warn"}>{identity.data?.oidc.ready ? "Ready" : "Activation required"}</Badge></div><div className="readiness-checks"><span className={identity.data?.oidc.issuerConfigured ? "ready" : ""}><i /> Issuer URL</span><span className={identity.data?.oidc.clientIdConfigured ? "ready" : ""}><i /> Client ID</span><span className={identity.data?.oidc.clientSecretConfigured ? "ready" : ""}><i /> Client secret</span></div><p>Configure these deployment values through protected project settings. Values are never rendered, persisted in connector metadata, or logged.</p></article><article className="console-card connector-readiness"><div className="card-heading"><div><p className="card-kicker">Lifecycle provisioning readiness</p><h2>SCIM 2.0</h2></div><Badge tone={identity.data?.scim.ready ? "good" : "warn"}>{identity.data?.scim.ready ? "Ready" : "Activation required"}</Badge></div><div className="readiness-checks"><span className={identity.data?.scim.baseUrlConfigured ? "ready" : ""}><i /> SCIM base URL</span><span className={identity.data?.scim.bearerTokenConfigured ? "ready" : ""}><i /> Bearer token</span></div><p>SCIM credentials stay in secure deployment configuration. This state provides only a Boolean readiness signal for administrators.</p></article><article className="console-card connector-readiness"><div className="card-heading"><div><p className="card-kicker">Vault prerequisite</p><h2>AppRole status</h2></div><Badge tone={vault.data?.connected ? "good" : "warn"}>{vault.data?.connected ? "Connected" : "Disconnected-safe"}</Badge></div><div className="readiness-checks"><span className={vault.data?.endpointConfigured ? "ready" : ""}><i /> VAULT_ADDR</span><span className={vault.data?.roleIdConfigured ? "ready" : ""}><i /> VAULT_ROLE_ID</span><span className={vault.data?.secretIdConfigured ? "ready" : ""}><i /> VAULT_SECRET_ID</span></div><p>All three values are customer-controlled deployment secrets. AgentFence exposes status only and does not accept credentials in this UI.</p></article></section>
  </PageFrame>;
}
